version: '3.5'
services:
  youtubedl:
    #restart: unless-stopped
    build:
      context: .
    environment:
        - TZ=Europe/Paris
        - QOBUZ_EMAIL=aa@bb.cc
        - QOBUZ_PASSWORD=abc
    ports:
      - "8080:80"
